apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: "spark-etl"
  namespace: project-user-bhargav-jitendra-das
spec:
  hadoopConf:
    fs.s3a.endpoint: http://local-s3-service.ezdata-system.svc.cluster.local:30000
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    fs.s3a.path.style.access: "true"
  sparkConf:
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.hadoop.fs.s3a.aws.credentials.provider: org.apache.spark.s3a.EzSparkAWSCredentialProvider
  type: Python
  sparkVersion: 3.5.2
  mode: cluster
  image: "lr1-bd-harbor-registry.mip.storage.hpecorp.net/develop/hpe-spark/spark:v3.5.2.4.0"
  imagePullPolicy: Always
  mainApplicationFile: "s3a://spark-test/spark_etl.py"
  restartPolicy:
    type: Never
  imagePullSecrets:
    - imagepull
  driver:
    labels:
      version: 3.5.2
    coreLimit: "1"
    cores: 1
    memory: 512m  
  executor:
    labels:
      version: 3.5.2
    coreLimit: "1"
    cores: 1
    memory: 512m
    instances: 1
