apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: "spark-etl"
  namespace: <username>
spec:
  sparkConf:
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.hadoop.fs.s3a.access.key: <access-key>
    spark.hadoop.fs.s3a.secret.key: s3
    spark.hadoop.fs.s3a.s3.client.factory.impl: org.apache.hadoop.fs.s3a.NonChunkedDefaultS3ClientFactory
    spark.driver.extraClassPath: /mounts/shared-volume/spark/disable-chunk-encoding-334.jar
    spark.executor.extraClassPath: /mounts/shared-volume/spark/disable-chunk-encoding-334.jar
    spark.hadoop.fs.s3a.bucket.ezua-demo.endpoint: http://local-s3-service.ezdata-system.svc.cluster.local:30000
  type: Python
  sparkVersion: 3.4.1
  mode: cluster
  image: "gcr.io/mapr-252711/spark-py-3.4.1:v3.4.1"
  imagePullPolicy: Always
  mainApplicationFile: "local:///mounts/shared-volume/spark/spark_etl_new.py"
  restartPolicy:
    type: Never
  imagePullSecrets:
    - imagepull
  driver:
    labels:
      version: 3.4.1
    volumeMounts:
      - name: <username>-volume
        mountPath: /mounts/<username>-volume
      - name: shared-volume
        mountPath: /mounts/shared-volume
  executor:
    labels:
      version: 3.4.1
    volumeMounts:
      - name: <username>-volume
        mountPath: /mounts/<username>-volume
      - name: shared-volume
        mountPath: /mounts/shared-volume
  volumes:
    - name: <username>-volume
      persistentVolumeClaim:
        claimName: user-pvc
    - name: shared-volume
      persistentVolumeClaim:
        claimName: kubeflow-shared-pvc
