name: "\U00002728 Enhancement"
description: Improve an existing tutorial/demo
labels:
  - enhancement
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        A clear and concise description of the enhancement proposal and why this is important.
    validations:
      required: true

  - type: textarea
    id: contribution
    attributes:
      label: Contribution
      description: |
        Is there any way that you could help, e.g. by submitting a PR?
        Make sure to read the [contribution guidelines](https://github.com/HPEEzmeral/ezua-tutorials/blob/develop/CONTRIBUTING.md).
    validations:
      required: true