name: bike-sharing
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy==1.19.5
    - pandas==1.4.4
    - seaborn==0.12.2
    - scikit-learn==1.0.1
    - boto3==1.20.24
    - jupyter==1.0.0
    - mlflow==2.1.1
