apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: data-transfer-mnist-s3-demo
  namespace: <username>
spec:
  sparkConf:
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.hadoop.fs.s3a.aws.credentials.provider: "org.apache.spark.s3a.EzSparkAWSCredentialProvider"
    spark.hadoop.fs.s3a.endpoint: http://local-s3-service.ezdata-system.svc.cluster.local:30000
  type: Scala
  sparkVersion: 3.5.1
  mode: cluster
  image: gcr.io/mapr-252711/spark-3.5.1:v3.5.1.0.5
  imagePullPolicy: Always
  mainApplicationFile: "local:///mounts/shared-volume/shared/ezua-tutorials/current-release/Data-Analytics/Spark/DataTransfer/DataTransfer.jar"
  mainClass: com.mapr.sparkdemo.DataTransfer
  arguments:
    - s3a://ezua-demo/data/mnist
    - binaryFile
    - file:///mounts/shared-volume/shared/mnist-spark-data
    - parquet
  restartPolicy:
    type: Never
  imagePullSecrets:
    - imagepull
  driver:
    labels:
      version: 3.5.1
    cores: 1
    coreLimit: "1"
    memory: 512m    
  executor:
    labels:
      version: 3.5.1
    cores: 1
    coreLimit: "1"
    memory: 512m
    instances: 1
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: kubeflow-shared-pvc
