apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: <username>
spec:
  type: Python
  sparkVersion: 3.5.0
  mode: cluster
  image: gcr.io/mapr-252711/spark-3.5.0:v3.5.0
  imagePullPolicy: Always
  mainApplicationFile: "local:///mounts/shared-volume/shared/ezua-tutorials/current-release/Data-Analytics/Spark/pi/pi.py"
  restartPolicy:
    type: Never
  imagePullSecrets:
    - imagepull
  driver:
    labels:
      version: 3.5.0
  executor:
    labels:
      version: 3.5.0
