apiVersion: v1
kind: Secret
metadata:
  name: kserver-minio-secret
  namespace: hpedemo-user01
  annotations:
     serving.kserve.io/s3-endpoint: "objectstore-zone1-svc.dataplatform.svc.cluster.local:9000/"
     serving.kserve.io/s3-usehttps: "1"
     serving.kserve.io/s3-verifyssl: "0"
     serving.kserve.io/s3-useanoncredential: "false"
     serving.kserve.io/s3-cabundle: ""
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-minio-sa
  namespace: hpedemo-user01
secrets:
- name: kserver-minio-secret