apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: data-process-transfer-demo
  namespace: <username>
spec:
  sparkConf:
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.mapr.extraconf.secret: "<k8s-secret-name>" 
    spark.hadoop.fs.s3a.s3.client.factory.impl: org.apache.hadoop.fs.s3a.NonChunkedDefaultS3ClientFactory
    spark.driver.extraClassPath: /mounts/shared-volume/spark/disable-chunk-encoding-334.jar
    spark.executor.extraClassPath: /mounts/shared-volume/spark/disable-chunk-encoding-334.jar
    spark.hadoop.fs.s3a.bucket.ezua-demo.endpoint: http://local-s3-service.ezdata-system.svc.cluster.local:30000
  type: Scala
  sparkVersion: 3.3.1
  mode: cluster
  image: gcr.io/mapr-252711/ezaf-spark-demo-example:fy23-q1
  imagePullPolicy: Always
  mainApplicationFile: local:///tmp/DataProcessTransfer.jar
  mainClass: com.mapr.sparkdemo.DataProcessTransfer
  arguments:
    - s3a://ezua-demo/data/financial-partitioned       # source path
    - parquet                                          # source format
    - file:///mounts/shared-volume/financial-processed # destination path
    - parquet                                          # destination format
  restartPolicy:
    type: Never
  imagePullSecrets:
    - imagepull
  driver:
    labels:
      version: 3.4.1
    volumeMounts:
      - name: shared-volume
        mountPath: /mounts/shared-volume
  executor:
    labels:
      version: 3.4.1
    volumeMounts:
      - name: shared-volume
        mountPath: /mounts/shared-volume
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: kubeflow-shared-pvc
        