apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-{{ts_nodash|replace("T", "")}}
spec:
  type: Scala
  sparkVersion: 3.5.1
  mode: cluster
  image: '{{dag_run.conf["airgap_registry_url"]|default("", True)}}gcr.io/mapr-252711/spark-3.5.1:v3.5.1.0.0'
  imagePullPolicy: Always
  imagePullSecrets:
  - imagepull
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/mapr/spark/spark-3.5.1/examples/jars/spark-examples_2.12-3.5.1.0-eep.jar"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.5.1
    volumeMounts:
      - name: shared-volume
        mountPath: /mounts/shared-volume/shared
  executor:
    cores: 1
    instances: 2
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.5.1
    volumeMounts:
      - name: shared-volume
        mountPath: /mounts/shared-volume/shared
    volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: kubeflow-shared-pvc
