apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: spark-fts-{{ts_nodash|replace("T", "")}}
spec:
  sparkConf:
    spark.driver.extraJavaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
    spark.executor.extraJavaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
  hadoopConf:
    fs.s3a.path.style.access: "true"
    fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    fs.s3a.endpoint: '{{dag_run.conf["s3_endpoint"]}}'
    fs.s3a.connection.ssl.enabled: '{{"true" if dag_run.conf["s3_endpoint_ssl_enabled"] else "false"}}'
  type: Scala
  sparkVersion: 3.5.0
  mode: cluster
  image: '{{dag_run.conf["airgap_registry_url"]|default("", True)}}gcr.io/mapr-252711/ezaf-spark-demo-example:fy24-q1-fts'
  imagePullPolicy: Always
  mainApplicationFile: local:///tmp/DataProcessTransfer.jar
  mainClass: com.mapr.sparkdemo.DataProcessTransfer
  arguments:
    - s3a://{{dag_run.conf["s3_bucket"]}}/{{dag_run.conf["s3_path"]}}
    - csv
    - file:///mnt/user/{{dag_run.conf["export_path"]}}
    - parquet
  restartPolicy:
    type: Never
  imagePullSecrets:
    - imagepull
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.5.0
    envFrom:
      - secretRef:
          name: '{{dag_run.conf["s3_secret_name"]}}'
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.5.0
    envFrom:
      - secretRef:
          name: '{{dag_run.conf["s3_secret_name"]}}'
