apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-oss-{{ts_nodash|replace("T", "")}}
spec:
  type: Python
  sparkVersion: '{{dag_run.conf["Spark-image-version"]}}'
  mode: cluster
  image: '{{dag_run.conf["Spark-image"]|default("", True)}}'
  imagePullPolicy: Always
  imagePullSecrets:
  - imagepull
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///mnt/shared/ezua-tutorials/current-release/Data-Analytics/Spark/pi/pi.py"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: '{{dag_run.conf["Spark-image-version"]}}'
  executor:
    cores: 1
    instances: 2
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: '{{dag_run.conf["Spark-image-version"]}}'
